nameOverride: ""
fullnameOverride: ""

nfsServer: "nfs.mydomain.lan"
volumes: 
 - name: data
   nfsPath: ""
   mountPath: "/data"
 - name: config
   nfsPath: ""
   mountPath: "/app/data/configs"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  host: ""
  className: ""
    # kubernetes.io/ingress.class: nginx
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific