apiVersion: apps/v1
kind: Deployment
metadata:
  name: homarr-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homarr-pod
  template:
    metadata:
      labels:
        app: homarr-pod
    spec:
      containers:
        - name: homarr
          image: ghcr.io/ajnart/homarr:latest
        
          ports:
            - name: ui
              containerPort: 7575
              protocol: TCP

          volumeMounts:
            {{- range .Values.persistence }}
            - name: {{- .name }}
              mountPath: {{- .mountPath }}
            {{- end }}

      volumes:
        {{- range .Values.persistence }}
        - name: {{- .name }}
            nfs:
              server: {{- .Values.nfsServer }}
              path: {{- .nfsPath }}
        {{- end }}