{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: homarr-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
    - host: {{- .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homarr-svc
                port:
                  name: ui
{{- end }}