apiVersion: v1
kind: Service
metadata:
  name: homarr-svc
  labels:
    {{- include "homarr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ui
      protocol: TCP
  selector:
    app: homarr-pod
